/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ufersa.controlConsult.gui;

import br.edu.ufersa.controlConsult.model.Consulta;
import br.edu.ufersa.controlConsult.model.HorarioAtendimento;
import br.edu.ufersa.controlConsult.model.Pessoa;
import java.util.Calendar;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author cassiano
 */
public class ConfirmarDataDaConsulta extends javax.swing.JFrame {

    /**
     * Creates new form ConfirmarDataDaConsulta
     */
    private Pessoa medico;
    private Pessoa paciente;

    public ConfirmarDataDaConsulta() {
        initComponents();
    }

    public ConfirmarDataDaConsulta(Pessoa paciente, Pessoa medico) {
        this.paciente = paciente;
        this.medico = medico;
        initComponents();
        if (medico.getMedico().getListaHorario().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O médico não possui horários de atendimento cadastrado");
        }
        int tamanho = medico.getMedico().getListaHorario().size();
        DefaultListModel model = new DefaultListModel();
        for (int cont = 0; cont < tamanho; cont++) {
            String elemento = "Dia da semana: " + medico.getMedico().getListaHorario().get(cont).getDiaSemana()
                    + "; Horario de início: " + String.valueOf(medico.getMedico().getListaHorario().get(cont).getInicio())
                    + ".";
            model.add(cont, elemento);
        }
        listaDeHorarios.setModel(model);
        nomeDoMedico.setEditable(false);
        especialidadeDoMedico.setEditable(false);
        nomeDoMedico.setText(medico.getNome());
        especialidadeDoMedico.setText(medico.getMedico().getEspecialidade().getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        nomeDoMedico = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        especialidadeDoMedico = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaDeHorarios = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        marcar = new javax.swing.JButton();
        data_jDateChooser = new com.toedter.calendar.JDateChooser();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Confirmação de Data da Consulta");

        nomeDoMedico.setEditable(false);
        nomeDoMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeDoMedicoActionPerformed(evt);
            }
        });

        jLabel1.setText("Médico:");

        jLabel2.setText("Especialidade:");

        especialidadeDoMedico.setEditable(false);
        especialidadeDoMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especialidadeDoMedicoActionPerformed(evt);
            }
        });

        listaDeHorarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(listaDeHorarios);

        jLabel3.setText("Data:");

        marcar.setText("Marcar");
        marcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcarActionPerformed(evt);
            }
        });

        data_jDateChooser.setMinimumSize(new java.awt.Dimension(120, 20));
        data_jDateChooser.setPreferredSize(new java.awt.Dimension(120, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(data_jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(marcar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(especialidadeDoMedico, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                            .addComponent(nomeDoMedico))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeDoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(especialidadeDoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(marcar)
                    .addComponent(data_jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void marcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcarActionPerformed
        // TODO add your handling code here:
        if (data_jDateChooser.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Informe um data válida para marcar a consulta");
        } else {
            if (listaDeHorarios.isSelectionEmpty()) {
                JOptionPane.showMessageDialog(this, "Selecione algum dos horários");
            } else {

                int posicao = listaDeHorarios.getSelectedIndex();
                Date agendada = data_jDateChooser.getDate();
                String diaSemanaListado = medico.getMedico().getListaHorario().get(posicao).getDiaSemana().getNome();
                Calendar cal = Calendar.getInstance();
                cal.setTime(agendada);
                String diaDaSemana = diaSemana(cal.get(Calendar.DAY_OF_WEEK));
                if (diaDaSemana.equals(diaSemanaListado)) {
                    long marcados = Consulta.numconsultaMarcado(medico.getMedico().getListaHorario().get(posicao), agendada);
                    if (marcados < 20l) {
                        if (Consulta.numconsultapaciente(medico.getMedico().getListaHorario().get(posicao), agendada, paciente.getPaciente()) == 0) {
                            JOptionPane.showMessageDialog(this, "Consulta marcada com sucesso, seu número de atendimento é: " + (marcados + 1));
                            Consulta con = new Consulta();
                            con.setAgendada(true);
                            con.setData_agendada(agendada);
                            con.setMedico(medico.getMedico());
                            con.setPaciente(paciente.getPaciente());
                            con.setHorario_atendimento(medico.getMedico().getListaHorario().get(posicao));
                            Date data_atual = new Date();
                            con.setData_marcado(data_atual);
                            con.create();
                        } else {
                            JOptionPane.showMessageDialog(this, "O paciente já agendou esta consulta");
                        }

                    } else {
                        JOptionPane.showMessageDialog(this, "O Atendimento para este dia encontra-se lotado.");
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "A data informada não corresponde a um dia da semana do horário selecionado");
                }
            }
        }

    }//GEN-LAST:event_marcarActionPerformed

    private void nomeDoMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeDoMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeDoMedicoActionPerformed

    private void especialidadeDoMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especialidadeDoMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_especialidadeDoMedicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmarDataDaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmarDataDaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmarDataDaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmarDataDaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmarDataDaConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser data_jDateChooser;
    private javax.swing.JTextField especialidadeDoMedico;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaDeHorarios;
    private javax.swing.JButton marcar;
    private javax.swing.JTextField nomeDoMedico;
    // End of variables declaration//GEN-END:variables

    public String diaSemana(int n) {
        String retorno = null;
        if (n == Calendar.SATURDAY) {
            retorno = "Sábado";
        }
        if (n == Calendar.MONDAY) {
            retorno = "Segunda-feira";
        }
        if (n == Calendar.TUESDAY) {
            retorno = "Terça-feira";
        }
        if (n == Calendar.WEDNESDAY) {
            retorno = "Quarta-feira";
        }
        if (n == Calendar.THURSDAY) {
            retorno = "Quinta-feira";
        }
        if (n == Calendar.FRIDAY) {
            retorno = "Sexta-feira";
        }
        if (n == Calendar.SUNDAY) {
            retorno = "Domingo";
        }
        return retorno;
    }

    private void confimar(HorarioAtendimento horario, Date agendada) {
        int numeroConsultas = getNumeroConsultasMarcadas(horario); // O número de consultas que o médico tem marcadas naquele horário
        int limiteConsultas = calcula(horario);
        if (numeroConsultas < limiteConsultas) {
            String mensagem = (numeroConsultas + 1) + "-ésima pessoa na fila";
            exibirConsultaValida(horario, agendada, mensagem);
        } else {
            String erro = "Horário lotado";
            exibirConsultaInvalida(erro);
        }
    }

    private int getNumeroConsultasMarcadas(HorarioAtendimento horario) {
        // Lógica para obter o número de consultas marcadas
        // Retorne o valor correto
        return 3;
    }


    private void exibirConsultaValida(HorarioAtendimento horario, Date agendada, String
    mensagem) {
    // Exibir tela de consulta válida com os parâmetros informados
    /*
    ConsultaValida tela = new
    ConsultaValida(horario.getInicio(),horario.getFim(),medico,agendada,mensagem);
    tela.setVisible(true);
    tela.setLocationRelativeTo(null);
    this.dispose();
    */
    }


    private void exibirConsultaInvalida(String erro) {
    // Exibir tela de consulta inválida com a mensagem de erro informada
    /*
    ConsultaInvalida tela = new ConsultaInvalida(medico, erro);
    tela.setVisible(true);
    tela.setLocationRelativeTo(null);
    this.dispose();
    */
    }

    private static final int CONSULTAS_POR_HORA = 6;

    private int calcula(HorarioAtendimento horario) {
        int horasInicio = horario.getInicio().getHours();
        int horasFim = horario.getFim().getHours();
        int diferencaHoras = horasInicio - horasFim;
        int consultas = diferencaHoras * CONSULTAS_POR_HORA;
        return consultas;
    }

}
