/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ufersa.controlConsult.gui;

import br.edu.ufersa.controlConsult.model.Paciente;
import br.edu.ufersa.controlConsult.model.Pessoa;
import br.edu.ufersa.controlConsult.model.validacao.CPF;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.NoResultException;
import javax.swing.JOptionPane;

/**
 *
 * @author juan
 */
public class FormPessoa extends javax.swing.JFrame {

    private void setTipoContexto(TipoContextoEnum tipoDeContexto) {
        this.tipoDeContexto = tipoDeContexto;
    }

    private void setTipoPessoa(TipoPessoaEnum tipoPessoa) {
        this.tipoDePessoa = tipoPessoa;
    }

    private void ajustarContextoPessoa() {
        // Ajustes na interface de acordo com cada contexto.
    }

    public static enum TipoPessoaEnum {
        AMBOS, PACIENTE, MEDICO;
    }

    public static enum UF_Enum {
        AC("Acre"), AL("Alagoas"), AP("Amapá"), AM("Amazonas"), BA("Bahia"), CE("Ceará"), DF("Distrito Federal"), ES(
                "Espírito Santo"), GO("Goiás"), MA("Maranhão"), MT("Mato Grosso"), MS("Mato Grosso do Sul"), MG(
                "Minas Gerais"), PA("Pará"), PB("Paraíba"), PR("Paraná"), PE("Pernambuco"), PI("Piauí"), RJ(
                "Rio de Janeiro"), RN("Rio Grande do Norte"), RS("Rio Grande do Sul"), RO(
                "Rondônia"), RR("Roraima"), SC(
                "Santa Catarina"), SP("São Paulo"), SE("Sergipe"), TO("Tocantins");
        private String name;

        private UF_Enum(String name) {
            this.name = name;
        }

        public String getName() {
            return this.name;
        }
    }

    public static enum TipoContextoEnum {
        /**
         * Inserir pessoa no sistema
         */
        CADASTRAR,
        /**
         * Atualizar pessoa no sistema.
         */
        ATUALIZAR;
    }

    private TipoPessoaEnum tipoDePessoa;
    private TipoContextoEnum tipoDeContexto;

    private Pessoa pessoa; // Pessoa para alteração. Valida somente se o contexto for para alteração.

    /**
     * Creates new form FormPessoa
     */
    public FormPessoa(TipoContextoEnum tipoContexto, TipoPessoaEnum tipoPessoa) {
        this.setTipoContexto(tipoContexto);
        this.setTipoPessoa(tipoPessoa);
        initComponents();
        ajustarContextoPessoa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        sexo_buttonGroup = new javax.swing.ButtonGroup();
        formulario_jPanel = new javax.swing.JPanel();
        pessoa_jPanel = new javax.swing.JPanel();
        nome_jLabel = new javax.swing.JLabel();
        nome_textField = new javax.swing.JTextField();
        rg_textField = new javax.swing.JTextField();
        logradouro_jLabel = new javax.swing.JLabel();
        logradouro_textField = new javax.swing.JTextField();
        cep_jLabel = new javax.swing.JLabel();
        cep_formattedField = new javax.swing.JFormattedTextField();
        nascimento_jLabel = new javax.swing.JLabel();
        nascimento_DateField = new com.toedter.calendar.JDateChooser();
        rg_jLabel = new javax.swing.JLabel();
        cpf_jLabel = new javax.swing.JLabel();
        cpf_textField = new javax.swing.JFormattedTextField();
        telefone_formattedField = new javax.swing.JFormattedTextField();
        bairro_jLabel = new javax.swing.JLabel();
        bairroField = new javax.swing.JTextField();
        cidade_jLabel = new javax.swing.JLabel();
        cidadeField = new javax.swing.JTextField();
        telefone_jLabel = new javax.swing.JLabel();
        masculino_radioButton = new javax.swing.JRadioButton();
        feminino_radioButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        email_jLabel = new javax.swing.JLabel();
        email_textField = new javax.swing.JTextField();
        estado_jLabel = new javax.swing.JLabel();
        estado_textField = new javax.swing.JTextField();
        medico_jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        chField = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jComboBox_espField = new javax.swing.JComboBox<>();
        paciente_jPanel7 = new javax.swing.JPanel();
        sus_jLabel = new javax.swing.JLabel();
        sus_formattedtField = new javax.swing.JFormattedTextField();
        botoes_jPanel = new javax.swing.JPanel();
        search_jButton = new javax.swing.JButton();
        submit_jButton = new javax.swing.JButton();
        cancel_jButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        formulario_jPanel.setLayout(new java.awt.GridLayout(3, 0));

        pessoa_jPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Pessoa"));
        java.awt.GridBagLayout pessoa_jPanelLayout = new java.awt.GridBagLayout();
        pessoa_jPanelLayout.columnWidths = new int[] {0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0};
        pessoa_jPanelLayout.rowHeights = new int[] {0, 1, 0, 1, 0, 1, 0, 1, 0};
        pessoa_jPanel.setLayout(pessoa_jPanelLayout);

        nome_jLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nome_jLabel.setText("Nome:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pessoa_jPanel.add(nome_jLabel, gridBagConstraints);

        nome_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_textFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        pessoa_jPanel.add(nome_textField, gridBagConstraints);

        rg_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rg_textFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 112;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        pessoa_jPanel.add(rg_textField, gridBagConstraints);

        logradouro_jLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logradouro_jLabel.setText("Logradouro: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pessoa_jPanel.add(logradouro_jLabel, gridBagConstraints);

        logradouro_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logradouro_textFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        pessoa_jPanel.add(logradouro_textField, gridBagConstraints);

        cep_jLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cep_jLabel.setText("CEP:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pessoa_jPanel.add(cep_jLabel, gridBagConstraints);

        try {
            cep_formattedField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cep_formattedField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cep_formattedFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 3);
        pessoa_jPanel.add(cep_formattedField, gridBagConstraints);

        nascimento_jLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nascimento_jLabel.setText("Nascimento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pessoa_jPanel.add(nascimento_jLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        pessoa_jPanel.add(nascimento_DateField, gridBagConstraints);

        rg_jLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rg_jLabel.setText("RG:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pessoa_jPanel.add(rg_jLabel, gridBagConstraints);

        cpf_jLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cpf_jLabel.setText("CPF:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pessoa_jPanel.add(cpf_jLabel, gridBagConstraints);

        try {
            cpf_textField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpf_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpf_textFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 3);
        pessoa_jPanel.add(cpf_textField, gridBagConstraints);

        try {
            telefone_formattedField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telefone_formattedField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefone_formattedFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        pessoa_jPanel.add(telefone_formattedField, gridBagConstraints);

        bairro_jLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bairro_jLabel.setText("Bairro:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pessoa_jPanel.add(bairro_jLabel, gridBagConstraints);

        bairroField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bairroFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        pessoa_jPanel.add(bairroField, gridBagConstraints);

        cidade_jLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cidade_jLabel.setText("Cidade:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pessoa_jPanel.add(cidade_jLabel, gridBagConstraints);

        cidadeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidadeFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        pessoa_jPanel.add(cidadeField, gridBagConstraints);

        telefone_jLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        telefone_jLabel.setText("Telefone:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pessoa_jPanel.add(telefone_jLabel, gridBagConstraints);

        sexo_buttonGroup.add(masculino_radioButton);
        masculino_radioButton.setText("Masculino");
        masculino_radioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masculino_radioButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 0;
        pessoa_jPanel.add(masculino_radioButton, gridBagConstraints);

        sexo_buttonGroup.add(feminino_radioButton);
        feminino_radioButton.setText("Feminino");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 0;
        pessoa_jPanel.add(feminino_radioButton, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Sexo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pessoa_jPanel.add(jLabel1, gridBagConstraints);

        email_jLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        email_jLabel.setText("E-mail:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pessoa_jPanel.add(email_jLabel, gridBagConstraints);

        email_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_textFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        pessoa_jPanel.add(email_textField, gridBagConstraints);

        estado_jLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        estado_jLabel.setText("Estado:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pessoa_jPanel.add(estado_jLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        pessoa_jPanel.add(estado_textField, gridBagConstraints);

        formulario_jPanel.add(pessoa_jPanel);

        medico_jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Médico"));
        medico_jPanel6.setLayout(new java.awt.GridBagLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Carga Horária:");
        medico_jPanel6.add(jLabel4, new java.awt.GridBagConstraints());

        try {
            chField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        chField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 75;
        medico_jPanel6.add(chField, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Especialidade:");
        medico_jPanel6.add(jLabel11, new java.awt.GridBagConstraints());

        jComboBox_espField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Geral", "Oftalmologia", "Psiquiatria" }));
        medico_jPanel6.add(jComboBox_espField, new java.awt.GridBagConstraints());

        formulario_jPanel.add(medico_jPanel6);

        paciente_jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Paciente"));
        paciente_jPanel7.setLayout(new java.awt.GridBagLayout());

        sus_jLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sus_jLabel.setText("Número de Registro SUS:");
        paciente_jPanel7.add(sus_jLabel, new java.awt.GridBagConstraints());

        try {
            sus_formattedtField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("### #### #### ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        sus_formattedtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sus_formattedtFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        paciente_jPanel7.add(sus_formattedtField, gridBagConstraints);

        formulario_jPanel.add(paciente_jPanel7);

        getContentPane().add(formulario_jPanel, java.awt.BorderLayout.CENTER);

        search_jButton.setText("Buscar");
        search_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_jButtonActionPerformed(evt);
            }
        });
        botoes_jPanel.add(search_jButton);

        submit_jButton.setText("Cadastrar ou Alterar");
        submit_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_jButtonActionPerformed(evt);
            }
        });
        botoes_jPanel.add(submit_jButton);

        cancel_jButton.setText("Cancelar");
        cancel_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_jButtonActionPerformed(evt);
            }
        });
        botoes_jPanel.add(cancel_jButton);

        getContentPane().add(botoes_jPanel, java.awt.BorderLayout.SOUTH);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nome_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_textFieldActionPerformed

    private void cpf_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpf_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpf_textFieldActionPerformed

    private void rg_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rg_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rg_textFieldActionPerformed

    private void telefone_formattedFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefone_formattedFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefone_formattedFieldActionPerformed

    private void logradouro_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logradouro_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logradouro_textFieldActionPerformed

    private void bairroFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bairroFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bairroFieldActionPerformed

    private void cidadeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidadeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidadeFieldActionPerformed

    private void cep_formattedFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cep_formattedFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cep_formattedFieldActionPerformed

    private void submit_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_jButtonActionPerformed
        switch (tipoDeContexto) {
            case CADASTRAR:
                switch (tipoDePessoa) {
                    case MEDICO:
                        cadastrarMedico();
                        break;
                    case PACIENTE:
                        cadastrarPaciente();
                        break;
                }
                break;
            case ATUALIZAR:
                switch (tipoDePessoa) {
                    case MEDICO:
                        atualizarMedico();
                        break;
                    case PACIENTE:
                        atualizarPaciente();
                        break;
                }
                break;
            default:
        }


    }//GEN-LAST:event_submit_jButtonActionPerformed

    private void cadastrarMedico() {
        if (!cpf_textField.getText().isEmpty() && !nome_textField.getText().isEmpty() && !rg_textField.getText().isEmpty() && nascimento_DateField.getDate() != null) {
            if (CPF.isCPF(cpf_textField.getText().replaceAll("[.-]", ""))) {
                String nome = nome_textField.getText();
                String cpf = cpf_textField.getText();
                String rg = rg_textField.getText();
                String email = ""; //TODO
                char sexo = 'm'; //TODO
                Date data_nascimento = nascimento_DateField.getDate();
                String telefone = telefone_formattedField.getText();
                String logradouro = logradouro_textField.getText();
                int numCasa = -1; //TODO
                String bairro = bairroField.getText();
                String cidade = cidadeField.getText();
                String estado = ""; //TODO
                String cep = cep_formattedField.getText();
                Pessoa p = new Pessoa(nome, cpf, rg, email, sexo, data_nascimento, telefone, logradouro, numCasa, bairro, cidade, estado, cep);
                p.setPaciente(new Paciente(sus_formattedtField.getText()));
                try {
                    if (Pessoa.findByCPF(cpf_textField.getText()) == null) {
                        p.update();
                        JOptionPane.showMessageDialog(this, "Paciente armazenado com sucesso");
                    } else {
                        JOptionPane.showMessageDialog(this, "O paciente já encontra-se cadastrado");
                    }
                } catch (NoResultException ex) {
                    Logger.getLogger(FormPessoa.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else {
                JOptionPane.showMessageDialog(this, "CPF inválido");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Informe os campos obrigattórios nome, CPF,\n"
                    + "RG e data de nascimento");
        }
    }

    private void cadastrarPaciente() {
        if (!cpf_textField.getText().isEmpty() && !nome_textField.getText().isEmpty() && !rg_textField.getText().isEmpty() && nascimento_DateField.getDate() != null) {
            if (CPF.isCPF(cpf_textField.getText().replaceAll("[.-]", ""))) {
                String nome = nome_textField.getText();
                String cpf = cpf_textField.getText();
                String rg = rg_textField.getText();
                String email = ""; //TODO
                char sexo = 'm'; //TODO
                Date dataDeNascimento = nascimento_DateField.getDate();
                String telefone = telefone_formattedField.getText();
                String logradouro = logradouro_jLabel.getText();
                int numCasa = -1; //TODO 
                String bairro = bairroField.getText();
                String cidade = cidadeField.getText();
                String estado = ""; //TODO
                String cep = cep_formattedField.getText();
                Pessoa p = new Pessoa(nome, cpf, rg, email, sexo, dataDeNascimento, telefone, logradouro, numCasa, bairro, cidade, estado, cep);
                p.setPaciente(new Paciente(sus_formattedtField.getText()));
                try {
                    if (Pessoa.findByCPF(cpf_textField.getText()) == null) {
                        p.update();
                        JOptionPane.showMessageDialog(this, "Paciente armazenado com sucesso");
                    } else {
                        JOptionPane.showMessageDialog(this, "O paciente já encontra-se cadastrado");
                    }
                } catch (NoResultException ex) {
                    Logger.getLogger(FormPessoa.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else {
                JOptionPane.showMessageDialog(this, "CPF inválido");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Informe os campos obrigattórios nome, CPF,\n"
                    + "RG e data de nascimento");
        }
    }

    private void atualizarMedico() {
        try {
            Pessoa duplicated_pessoa = Pessoa.findByCPF(cpf_textField.getText());
        } catch (NoResultException ex) {
            Logger.getLogger(FormPessoa.class.getName()).log(Level.SEVERE, null, ex);
            Pessoa duplicated_pessoa = null;
        }
        if (pessoa.getMedico() == null) {
            JOptionPane.showMessageDialog(null, "Médico não encontrado");
        } else {
            updateVarPessoa();
            updateVarPessoaMedico();

        }
    }

    private void atualizarPaciente() {
        if (pessoa == null) {
            JOptionPane.showMessageDialog(this, "Informe o CPF do paciente que deseja atualizar as informações cadastrais");
        } else {
            updateVarPessoa();
            updateVarPessoaPaciente();
        }
    }

    private void updateVarPessoa() {
        String nome = pessoa.getNome();
        String cpf = pessoa.getCpf();
        String rg = pessoa.getRg();
        String email = ""; //TODO
        char sexo = 'm'; //TODO
        Date dataDeNascimento = pessoa.getDataDeNascimento();
        String telefone = telefone_formattedField.getText();
        String logradouro = logradouro_textField.getText();
        int numCasa = -1; //TODO 
        String bairro = bairroField.getText();
        String cidade = cidadeField.getText();
        String estado = ""; //TODO
        String cep = cep_formattedField.getText();
        // TODO: atualizar Pessoa

    }

    private void updateVarPessoaMedico() {
        chField.setText(String.valueOf(pessoa.getMedico().getCargaHoraria()));
        chField.setEditable(true);
        jComboBox_espField.setSelectedItem(pessoa.getMedico().getEspecialidade()); //TODO
    }

    private void updateVarPessoaPaciente() {
        String num_sus = sus_formattedtField.getText();

        Paciente pn = new Paciente(num_sus);
        pessoa.setPaciente(pn);
        pessoa.update();
        JOptionPane.showMessageDialog(this, "Paciente Atualizado com Sucesso");
        pessoa = pn.getPessoa();
    }
    private void sus_formattedtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sus_formattedtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sus_formattedtFieldActionPerformed

    private void cancel_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_jButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancel_jButtonActionPerformed

    private void chFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chFieldActionPerformed

    private void search_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_jButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_jButtonActionPerformed

    private void masculino_radioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masculino_radioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masculino_radioButtonActionPerformed

    private void email_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_textFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPessoa(
                        TipoContextoEnum.CADASTRAR,
                        TipoPessoaEnum.MEDICO
                ).setVisible(true);
            }
        });
    }

    private void updateFrameAction() {
        // TODO Auto-generated method stub
//        SearchPerson.getInstance(this);
    }

    private FormPessoa.UF_Enum getUF(String uf) {
        // TODO Auto-generated method stub

        FormPessoa.UF_Enum[] values = FormPessoa.UF_Enum.values();
        for (FormPessoa.UF_Enum f : values) {
            if (f.getName().equals(uf)) {
                return f;
            }
        }
        return null;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bairroField;
    private javax.swing.JLabel bairro_jLabel;
    private javax.swing.JPanel botoes_jPanel;
    private javax.swing.JButton cancel_jButton;
    private javax.swing.JFormattedTextField cep_formattedField;
    private javax.swing.JLabel cep_jLabel;
    private javax.swing.JFormattedTextField chField;
    private javax.swing.JTextField cidadeField;
    private javax.swing.JLabel cidade_jLabel;
    private javax.swing.JLabel cpf_jLabel;
    private javax.swing.JFormattedTextField cpf_textField;
    private javax.swing.JLabel email_jLabel;
    private javax.swing.JTextField email_textField;
    private javax.swing.JLabel estado_jLabel;
    private javax.swing.JTextField estado_textField;
    private javax.swing.JRadioButton feminino_radioButton;
    private javax.swing.JPanel formulario_jPanel;
    private javax.swing.JComboBox<String> jComboBox_espField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel logradouro_jLabel;
    private javax.swing.JTextField logradouro_textField;
    private javax.swing.JRadioButton masculino_radioButton;
    private javax.swing.JPanel medico_jPanel6;
    private com.toedter.calendar.JDateChooser nascimento_DateField;
    private javax.swing.JLabel nascimento_jLabel;
    private javax.swing.JLabel nome_jLabel;
    private javax.swing.JTextField nome_textField;
    private javax.swing.JPanel paciente_jPanel7;
    private javax.swing.JPanel pessoa_jPanel;
    private javax.swing.JLabel rg_jLabel;
    private javax.swing.JTextField rg_textField;
    private javax.swing.JButton search_jButton;
    private javax.swing.ButtonGroup sexo_buttonGroup;
    private javax.swing.JButton submit_jButton;
    private javax.swing.JFormattedTextField sus_formattedtField;
    private javax.swing.JLabel sus_jLabel;
    private javax.swing.JFormattedTextField telefone_formattedField;
    private javax.swing.JLabel telefone_jLabel;
    // End of variables declaration//GEN-END:variables
}
