/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ufersa.controlConsult.gui;

/**
 *
 * @author asus
 */
public class MostraDesempenho extends javax.swing.JFrame {

    /**
     * Creates new form MostraDesempenho
     */
    public MostraDesempenho() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nome_jLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        nome_jLabel1 = new javax.swing.JLabel();
        nome_jLabel2 = new javax.swing.JLabel();
        nome_jLabel3 = new javax.swing.JLabel();
        nome_jLabel4 = new javax.swing.JLabel();
        numero_paciente_atual = new javax.swing.JLabel();
        numero_paciente_atual1 = new javax.swing.JLabel();
        numero_paciente_atual2 = new javax.swing.JLabel();
        numero_paciente_atual3 = new javax.swing.JLabel();
        nome_medico = new javax.swing.JLabel();
        nome_medico1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setText("Desempenho Médico");

        nome_jLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nome_jLabel.setText("Nome:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Especialidade:");

        nome_jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nome_jLabel1.setText("Quantidade de Faltas:");

        nome_jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nome_jLabel2.setText("Média de Tempo em Consulta:");

        nome_jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nome_jLabel3.setText("Média de Horários de Chegada e Saída:");

        nome_jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nome_jLabel4.setText("Quantidade de Atrasos:");

        numero_paciente_atual.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        numero_paciente_atual.setText("_____");

        numero_paciente_atual1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        numero_paciente_atual1.setText("_____");

        numero_paciente_atual2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        numero_paciente_atual2.setText("_____");

        numero_paciente_atual3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        numero_paciente_atual3.setText("_____");

        nome_medico.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        nome_medico.setText("___________");

        nome_medico1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        nome_medico1.setText("___________");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nome_jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numero_paciente_atual))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nome_jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numero_paciente_atual2))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nome_medico1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nome_jLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nome_medico))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nome_jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numero_paciente_atual3))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nome_jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numero_paciente_atual1)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nome_jLabel)
                    .addComponent(nome_medico))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(nome_medico1))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome_jLabel1)
                    .addComponent(numero_paciente_atual))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nome_jLabel2)
                    .addComponent(numero_paciente_atual2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nome_jLabel3)
                    .addComponent(numero_paciente_atual1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nome_jLabel4)
                    .addComponent(numero_paciente_atual3))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostraDesempenho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostraDesempenho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostraDesempenho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostraDesempenho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostraDesempenho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nome_jLabel;
    private javax.swing.JLabel nome_jLabel1;
    private javax.swing.JLabel nome_jLabel2;
    private javax.swing.JLabel nome_jLabel3;
    private javax.swing.JLabel nome_jLabel4;
    private javax.swing.JLabel nome_medico;
    private javax.swing.JLabel nome_medico1;
    private javax.swing.JLabel numero_paciente_atual;
    private javax.swing.JLabel numero_paciente_atual1;
    private javax.swing.JLabel numero_paciente_atual2;
    private javax.swing.JLabel numero_paciente_atual3;
    // End of variables declaration//GEN-END:variables
}
